routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\Couponcontroller;
use App\Http\Controllers\Admin\OrderController as AdminOrderController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Clients\OrderController as ClientOrderController ;
use App\Http\Controllers\Clients\CartController;
use App\Http\Controllers\Clients\ClientProductController;
use App\Http\Controllers\Clients\HomeController;

use Spatie\Permission\Middlewares\RoleMiddleware;
use Spatie\Permission\Middlewares\PermissionMiddleware;
use Spatie\Permission\Middlewares\RoleOrPermissionMiddleware;

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//Route client 
Route::get('/', [HomeController::class, 'index'])->name('client.home');

Route::get('product/{category_id}', [ClientProductController::class, 'index'])
->name('client.products.index');

Route::get('product-detail/{id}', [ClientProductController::class, 'show'])
->name('client.products.show');

Route::middleware('auth')->group(function(){
    
    Route::post('add-to-cart', [CartController::class, 'store'])->name('client.carts.add');

    Route::get('carts', [CartController::class, 'index'])->name('client.carts.index');

    Route::post('update-quantity-product-in-cart/{cart_product_id}', [CartController::class, 'updateQuantityProduct'])
    ->name('client.carts.update_product_quantity');

    Route::post('remove-product-in-cart/{cart_product_id}',[ CartController::class, 'removeProductInCart'])
    ->name('client.carts.remove_product');

    Route::post('apply-coupon', [CartController::class, 'applyCoupon'])
    ->name('client.carts.apply_coupon');

    Route::get('checkout', [CartController::class, 'checkout'])
    ->name('client.checkout.index')
    ->middleware('user.can_checkout_cart');
    
    Route::post('process-checkout', [CartController::class, 'processCheckout'])
    ->name('client.checkout.proccess')
    ->middleware('user.can_checkout_cart');

    Route::get('list-order', [ClientOrderController::class, 'index' ])
    ->name('client.orders.index');

    Route::get('orders/cancel/{id}', [ClientOrderController::class, 'cancelOrder' ])
    ->name('client.orders.cancel');

});

Auth::routes();


//Route admin 
Route::middleware('auth')->group(function(){

    Route::get('/dasboard', function () {
        return view('admin.dashboard.index');})->name('dasboard');

    
    // Route::resource('roles', RoleController::class);
    Route::prefix('roles')->controller(RoleController::class)->name('roles.')->group(function(){
        Route::get('/', 'index')->name('index')->middleware('role:super-admin');
        Route::post('/', 'store')->name('store')->middleware('role:super-admin');
        Route::get('/create', 'create')->name('create')->middleware('role:super-admin');
        Route::get('/{coupon}', 'show')->name('show')->middleware('role:super-admin');
        Route::put('/{coupon}', 'update')->name('update')->middleware('role:super-admin');
        Route::delete('/{coupon}', 'destroy')->name('destroy')->middleware('role:super-admin');
        Route::get('/{coupon}/edit', 'edit')->name('edit')->middleware('role:super-admin');
    });


    // Route::resource('users', UserController::class);
    Route::prefix('users')->controller(UserController::class)->name('users.')->group(function(){
        Route::get('/', 'index')->name('index')->middleware('permission:show-user');
        Route::post('/', 'store')->name('store')->middleware('permission:create-user');
        Route::get('/create', 'create')->name('create')->middleware('permission:create-user');
        Route::get('/{coupon}', 'show')->name('show')->middleware('permission:show-user');
        Route::put('/{coupon}', 'update')->name('update')->middleware('permission:update-user');
        Route::delete('/{coupon}', 'destroy')->name('destroy')->middleware('permission:delete-user');
        Route::get('/{coupon}/edit', 'edit')->name('edit')->middleware('permission:update-user');
    });


    // Route::resource('categories', CategoryController::class);
    Route::prefix('categories')->controller(CategoryController::class)->name('categories.')->group(function(){
        Route::get('/', 'index')->name('index')->middleware('permission:show-category');
        Route::post('/', 'store')->name('store')->middleware('permission:create-category');
        Route::get('/create', 'create')->name('create')->middleware('permission:create-category');
        Route::get('/{coupon}', 'show')->name('show')->middleware('permission:show-category');
        Route::put('/{coupon}', 'update')->name('update')->middleware('permission:update-category');
        Route::delete('/{coupon}', 'destroy')->name('destroy')->middleware('permission:delete-category');
        Route::get('/{coupon}/edit', 'edit')->name('edit')->middleware('permission:update-category');
    });


    // Route::resource('products', ProductController::class);
    Route::prefix('products')->controller(ProductController::class)->name('products.')->group(function(){
        Route::get('/', 'index')->name('index')->middleware('permission:show-product');
        Route::post('/', 'store')->name('store')->middleware('permission:create-product');
        Route::get('/create', 'create')->name('create')->middleware('permission:create-product');
        Route::get('/{coupon}', 'show')->name('show')->middleware('permission:show-product');
        Route::put('/{coupon}', 'update')->name('update')->middleware('permission:update-product');
        Route::delete('/{coupon}', 'destroy')->name('destroy')->middleware('permission:delete-product');
        Route::get('/{coupon}/edit', 'edit')->name('edit')->middleware('permission:update-product');
    });


    // Route::resource('coupons', Couponcontroller::class);
    Route::prefix('coupons')->controller(Couponcontroller::class)->name('coupons.')->group(function(){
        Route::get('/', 'index')->name('index')->middleware('permission:show-coupon');
        Route::post('/', 'store')->name('store')->middleware('permission:create-coupon');
        Route::get('/create', 'create')->name('create')->middleware('permission:create-coupon');
        Route::get('/{coupon}', 'show')->name('show')->middleware('permission:show-coupon');
        Route::put('/{coupon}', 'update')->name('update')->middleware('permission:update-coupon');
        Route::delete('/{coupon}', 'destroy')->name('destroy')->middleware('permission:delete-coupon');
        Route::get('/{coupon}/edit', 'edit')->name('edit')->middleware('permission:update-coupon');
    });


    Route::get('orders', [AdminOrderController::class, 'index'])
    ->name('admin.orders.index');
    // ->middleware('list-order');

    // Route::post('update-status/{id}', [AdminOrderController::class, 'updateStatus'])
    // ->name('admin.orders.update_status');
});

resources/views/admin/layout/sidebar.blade.php
<aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark" id="sidenav-main">
    <div class="sidenav-header">
      <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
      <a class="navbar-brand m-0" href=" https://demos.creative-tim.com/material-dashboard/pages/dashboard " target="_blank">
        {{-- <img src="./assets/img/logo-ct.png" class="navbar-brand-img h-100" alt="main_logo"> --}}
        <span class="ms-1 font-weight-bold text-white">Hello: {{ auth()->user()->name }}</span>
      </a>
    </div>
    <hr class="horizontal light mt-0 mb-2">
    <div class="collapse navbar-collapse  w-auto  max-height-vh-100" id="sidenav-collapse-main">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link text-white  {{ request()->routeIs('dasboard')? 'bg-gradient-primary active' : ''}}" 
            href="{{ route('dasboard') }}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">dashboard</i>
            </div>
            <span class="nav-link-text ms-1">Dashboard</span>
          </a>
        </li>

        @hasrole('super-admin')
          <li class="nav-item">
            <a class="nav-link text-white {{ request()->routeIs('roles.*')? 'bg-gradient-primary active' : ''}} " 
              href="{{ route('roles.index') }}">
              <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <i class="material-icons opacity-10">table_view</i>
              </div>
              <span class="nav-link-text ms-1">Role</span>
            </a>
          </li>
        @endhasrole
        
        @can('show-coupon')
          <li class="nav-item">
            <a class="nav-link text-white {{ request()->routeIs('users.*')? 'bg-gradient-primary active' : ''}} " 
              href="{{ route('users.index') }}">
              <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <i class="material-icons opacity-10">receipt_long</i>
              </div>
              <span class="nav-link-text ms-1">User</span>
            </a>
          </li>
        @endcan

        @can('show-product')
          <li class="nav-item">
            <a class="nav-link text-white {{ request()->routeIs('products.*')? 'bg-gradient-primary active' : ''}} " 
              href="{{ route('products.index') }}">
              <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <i class="material-icons opacity-10">view_in_ar</i>
              </div>
              <span class="nav-link-text ms-1">Product</span>
            </a>
          </li>
        @endcan

        @can('show-category')
          <li class="nav-item">
            <a class="nav-link text-white {{ request()->routeIs('categories.*')? 'bg-gradient-primary active' : ''}} " 
              href="{{ route('categories.index') }}">
              <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <i class="material-icons opacity-10">format_textdirection_r_to_l</i>
              </div>
              <span class="nav-link-text ms-1">Category</span>
            </a>
          </li>
        @endcan

        @can('show-coupon')
          <li class="nav-item">
            <a class="nav-link text-white {{ request()->routeIs('coupons.*')? 'bg-gradient-primary active' : ''}} " 
              href="{{ route('coupons.index') }}">
              <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <i class="material-icons opacity-10">format_textdirection_r_to_l</i>
              </div>
              <span class="nav-link-text ms-1">Coupons</span>
            </a>
          </li>
        @endcan

        @can('list-order')
          <li class="nav-item">
            <a class="nav-link text-white {{ request()->routeIs('orders.*')? 'bg-gradient-primary active' : ''}} " 
              href="{{ route('admin.orders.index') }}">
              <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <i class="material-icons opacity-10">table_view</i>
              </div>
              <span class="nav-link-text ms-1">Order</span>
            </a>
          </li>
        @endcan
      </ul>
    </div>
  </aside>